repos:
  - repo: https://github.com/pre-commit/mirrors-prettier
    rev: v3.1.0
    hooks:
      - id: prettier
        name: Format html files
        files: \.html$
        additional_dependencies:
          - prettier@3.3.3
